vich_uploader:
    db_driver: orm

        mappings:
             screenshot_reclamation:
                  uri_prefix: /screenshot/reclamation
                  upload_destination: '%kernel.project_dir%/public/screenshot/reclamation'

