vich_uploader:
  db_driver: orm

  mappings:
    saloons:
      uri_prefix: /images/saloons
      upload_destination: '%kernel.project_dir%/public/images/saloons'
      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
